/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosupergiro;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SENA
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuGiro = new javax.swing.JMenuItem();
        menuConsultarGiro = new javax.swing.JMenuItem();
        menuConsultarMonto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuRegistrar = new javax.swing.JMenuItem();
        menuRetirarGiro = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosupergiro/supergiros.png"))); // NOI18N

        jMenu2.setText("Giro");

        menuGiro.setText("Hacer Giro");
        menuGiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGiroActionPerformed(evt);
            }
        });
        jMenu2.add(menuGiro);

        menuConsultarGiro.setText("Consultar Giros");
        menuConsultarGiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarGiroActionPerformed(evt);
            }
        });
        jMenu2.add(menuConsultarGiro);

        menuConsultarMonto.setText("Consultar Monto");
        menuConsultarMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarMontoActionPerformed(evt);
            }
        });
        jMenu2.add(menuConsultarMonto);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cliente");

        menuRegistrar.setText("Resgistrar Cliente");
        menuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarActionPerformed(evt);
            }
        });
        jMenu3.add(menuRegistrar);

        menuRetirarGiro.setText("Retirar Giro");
        menuRetirarGiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRetirarGiroActionPerformed(evt);
            }
        });
        jMenu3.add(menuRetirarGiro);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGiroActionPerformed
        FrmHacerGiros frm = new FrmHacerGiros(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_menuGiroActionPerformed

    private void menuConsultarGiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarGiroActionPerformed
        FrmListarGiros frm = new FrmListarGiros(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_menuConsultarGiroActionPerformed

    private void menuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarActionPerformed
        FrmRegistrarCliente frm = new FrmRegistrarCliente(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_menuRegistrarActionPerformed

    private void menuRetirarGiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRetirarGiroActionPerformed
        FrmRetirarGiro frm = new FrmRetirarGiro(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_menuRetirarGiroActionPerformed

    private void menuConsultarMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarMontoActionPerformed
        ArrayList<Giro> listaG = GetionGiro.listarGiro();
        double suma=0;
        for (Giro giro : listaG) {
            suma= suma+giro.getMonto();
        }
        JOptionPane.showMessageDialog(null, "El monto total es: " + suma);
    }//GEN-LAST:event_menuConsultarMontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuConsultarGiro;
    private javax.swing.JMenuItem menuConsultarMonto;
    private javax.swing.JMenuItem menuGiro;
    private javax.swing.JMenuItem menuRegistrar;
    private javax.swing.JMenuItem menuRetirarGiro;
    // End of variables declaration//GEN-END:variables
}
